name: Server CI

on:
  pull_request:
    branches:
      - main
    paths:
      - server/**

jobs:
  run-server-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./server

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - uses: ikalnytskyi/action-setup-postgres@v7
        id: postgres
        with:
          username: postgres
          password: postgres
          database: test-db
          port: 5432
          postgres-version: "17"

      - name: Package installation
        run: npm ci

      - name: Linting
        run: npm run lint

      - name: Decrypt large secret
        run: |
          pwd
          cat .env.test
          echo $TEST_ENV | base64 -d > .env.test
        env:
          TEST_ENV: ${{ secrets.SERVER_TEST_ENV }}

      - name: Run migration
        run: "npm run migrate:up"

      - name: Run database seed
        run: "npm run seed:run"

      - name: Run test
        run: npm test -- --detectOpenHandles

      - name: Run rollback
        run: "npm run migrate:down"
